apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-class
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local-dynamic
spec:
  storageClassName: local-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: dynamic-storage-pod
spec:
  containers:
    - name: storage-container
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh"]
      args: ["-c", "echo 'Data persisted dynamically' > /data-store/dynamic.txt && sleep infinity"]
      volumeMounts:
        - name: dynamic-volume
          mountPath: "/data-store"
  volumes:
    - name: dynamic-volume
      persistentVolumeClaim:
        claimName: pvc-local-dynamic