apiVersion: v2
name: petlclinc-app
type: application
description: A Helm chart for Kubernetes that deploys the PetClinic application.


# incase of CICD these values will be updated automatically by the pipeline
# incase of manual changes, these values should be updated manually by the developer

version: 0.1.0 # the beginning version of the chart
appVersion: "1.16.0" # the version number of the application being deployed, usualy it is the docker image version






