---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "S2FyaW1TdXBlclNlY3JldERhdGFiYXNlUm9vdFBhc3N3b3Jk"
  MYSQL_DATABASE: "S2FyaW1TdXBlclNlY3JldERhdGFiYXNlTmFtZQ=="
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-db
spec:
  containers:
  - name: mysql
    image: mysql:8.4.5
    imagePullPolicy: IfNotPresent
    envFrom:
    - secretRef:
        name: db-secrets
