apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-db-svc"
  namespace: {{.Values.namespace.name}}
  labels:
    tier: {{.Values.dbService.labels.tier}}
spec:
  type: ClusterIP
  selector:
    tier: {{.Values.dbService.selectorLabels.tier}}
  ports:
  - port: {{.Values.dbService.port}}
    targetPort: {{.Values.dbService.port}} 
