apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-app"
  namespace: {{.Values.namespace.name}}
  labels:
    tier: {{.Values.appDeployment.labels.tier}}
spec:
  replicas: {{.Values.appDeployment.replicaCount}}
  selector:
    matchLabels: 
      tier: {{.Values.appDeployment.selectorLabels.tier}}
  template:
    metadata:
      labels:
        tier: {{.Values.appDeployment.selectorLabels.tier}}
    spec:
      containers:
        - name: petclinic-app-container
          image: "{{.Values.appDeployment.image.repository}}:{{.Values.appDeployment.image.tag}}"
          imagePullPolicy: {{.Values.imagePullPolicy}}
          ports:
          - containerPort: {{.Values.appDeployment.port}}
        
          env: 
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://{{ .Release.Name }}-db-svc:{{.Values.dbService.port}}/{{.Values.database.env.MYSQL_DATABASE}}"
          
          - name: SPRING_DATASOURCE_USERNAME
            value: {{.Values.appDeployment.env.SPRING_DATASOURCE_USERNAME}}
          - name: SPRING_DATASOURCE_PASSWORD
            value: {{.Values.appDeployment.env.SPRING_DATASOURCE_PASSWORD}}
          - name: SPRING_PROFILES_ACTIVE
            value: {{.Values.appDeployment.env.SPRING_PROFILES_ACTIVE}}
          