apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-app-svc"
  namespace: {{.Values.namespace.name}}
  labels:
    tier: {{.Values.appService.labels.tier}}
spec:
  # type: ClusterIP
  type: {{.Values.appService.type}}
  selector: 
    tier: {{.Values.appService.selectorLabels.tier}}
  ports:
  - port: {{.Values.appService.port}}
    targetPort: {{.Values.appService.targetPort}}
    nodePort: {{.Values.appService.nodePort}}