apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: petclinic-ns
spec:
  storageClassName: manual
  volumeName: db-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi