apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: petclinic-ns
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://db-headless-svc:3306/petclinic
  SPRING_DATASOURCE_USERNAME: "petclinic"
  SPRING_PROFILES_ACTIVE: "mysql"