apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: petclinic-ns
  labels:
    tier: app
spec:
  replicas: 3
  selector:
    matchLabels: 
      tier: app
  template:
    metadata:
      labels:
        tier: app
    spec:
      initContainers:
      - name: init-db-container
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
        - |
          until nc -z -v -w1 db-headless-svc.petclinic-ns.svc.cluster.local 3306
          do
            echo "Waiting for MySQL to be ready..."
            sleep 2
          done
      
      containers:
      - name: petclinic-app-container
        image: springcommunity/spring-petclinic:3.5.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        
        envFrom:
        - configMapRef:
            name: app-configmap

        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: app-secrets
              key: SPRING_DATASOURCE_PASSWORD
       