apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01_namespace.yaml
  - 02_pv.yaml
  - 03_pvc.yaml
  - 04_db_secrets.yaml
  - 05_db_configmap.yaml
  - 06_db_service.yaml
  - 07_db_statefulset.yaml
  - 08_app_secrets.yaml
  - 09_app_configmap.yaml
  - 10_app_service.yaml
  - 11_app_deployment.yaml
  - 12_ingress.yaml

# kubectl apply -k simple_practical_projects/02_Spring_PetClinic/