apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  namespace: petclinic-namespace 
  labels:
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
  template:
    metadata:
      name: db-pod
      labels:
        tier: db
    spec:
      containers:
      - name: mydql-db-container
        image: mysql:8.4.5
        imagePullPolicy: IfNotPresent
        
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: petclinic
        - name: MYSQL_DATABASE
          value: petclinic
        - name: MYSQL_USER
          value: petclinic
        - name: MYSQL_PASSWORD
          value: petclinic 
        ports:
        - containerPort: 3306

