apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: petclinic-namespace
  labels:
    tier: app
spec:
  replicas: 3
  selector:
    matchLabels: 
      tier: app
  template:
    metadata:
      labels:
        tier: app
    spec:
      containers:
        - name: petclinic-app-container
          image: springcommunity/spring-petclinic:3.5.6
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
        
          env: 
          - name: SPRING_DATASOURCE_URL
            # connect to the db-svc service on port 3306 and use the petclinic database
            value: jdbc:mysql://db-svc:3306/petclinic 
            # value: "jdbc:mysql://db-svc.petclinic-namespace.svc.cluster.local:3306/petclinic?autoReconnect=true&failOverReadOnly=false&maxReconnects=10"
          
          - name: SPRING_DATASOURCE_USERNAME
            value: petclinic
          - name: SPRING_DATASOURCE_PASSWORD
            value: "petclinic"
          - name: SPRING_PROFILES_ACTIVE
            value: "mysql"
          # - name: SPRING_CLOUD_CONFIG_ENABLED
          #   value: "false"


