apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01_namespace.yaml
  - 02_db-deployment.yaml
  - 03_db-service.yaml
  - 04_app-deployment.yaml
  - 05_app-service.yaml

# kubectl apply -k simple_practical_projects/01_Spring_PetClinic/